[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-darth-sidious-vader-star-wars-artwork-digital-art-1920x1080-80661
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-darth-sidious-vader-star-wars-artwork-digital-art-1920x1080-80661
GtkTheme=oomox-darth-sidious-vader-star-wars-artwork-digital-art-1920x1080-80661
IconTheme=oomox-darth-sidious-vader-star-wars-artwork-digital-art-1920x1080-80661
MetacityTheme=oomox-darth-sidious-vader-star-wars-artwork-digital-art-1920x1080-80661
